### ISSUE TITLE
Could we just have 1 space world?

### ISSUE THREAD

**Issue by Mood-Lore** [Seggan/SlimefunWarfare#11]
I've been wracking my brain on where this random space world came from it's called "testy_space"
![image](https://user-images.githubusercontent.com/63960101/109442344-e7474480-7a72-11eb-90c6-dd534e7633f0.png)
"testy" world is a flat overworld, world. and "testy_space" is a void world.

**Comment by Seggan** [comment]
it generates one space world for every slimefun enabled world. will implement at an unknown time in the future

**Comment by ProfElements** [comment]
even better please have a world blacklist so that a world in the blacklist doesnt generate its corresponding space world^

**Comment by Seggan** [comment]
Space code removed in latest version
