### ISSUE TITLE
dummy and space fly problem

### ISSUE THREAD

**Issue by RIPISDRAD** [Seggan/SlimefunWarfare#12]
first the 2 problem about dummy!
1-when u right click on them it just give 2
2-can u make it like not a mob thing ( it detects its as a mob and if player build a lot of these and the server is weak its gonna make it laggy)
second when u came out of space u can still fly ! and that is the main reason why i said bug
if this is jut for teleportation then why the fly thing? (to get out  of the space i fell in the void)
i hope i showed the problem tbh just dont put fly in them its super annoying for the servers

**Comment by Seggan** [comment]
1st bug about the dummy is known, idk why it happens. 2nd bug abt dummy, i cant do anything else, sorry
