### ISSUE TITLE
world_space_space_space_space_space

### ISSUE THREAD

**Issue by RIPISDRAD** [Seggan/SlimefunWarfare#20]
i already told u about this bug so just saying again(if u need info i cant provide anything but these)
![2021-04-10_16 11 04](https://user-images.githubusercontent.com/76468672/115702779-93742000-a37e-11eb-87f1-f4884e670e2a.png)
![2021-04-10_16 11 00](https://user-images.githubusercontent.com/76468672/115702786-95d67a00-a37e-11eb-8898-09e034722c5d.png)

**Comment by Seggan** [comment]
i already said, will fix this when i get to sfwarfare

**Comment by RIPISDRAD** [comment]
Dont torcher me i reallly am tired of deleting them

**Comment by Seggan** [comment]
you can disable sfwarfare for now

**Comment by RIPISDRAD** [comment]
That's not an option when people use it

**Comment by Seggan** [comment]
Pushed a temporary fix for this will be available in next build

**Comment by RIPISDRAD** [comment]
Tnx man 👍 finally 3rd dimention is the last which we go ;)
