### ISSUE TITLE
Guide Book Bug/Dupe

### ISSUE THREAD

**Issue by MegalithOfficial** [Seggan/SlimefunWarfare#29]
There is a Dupe bug in /sf book (bug video in discord link)

https://cdn.discordapp.com/attachments/624966637816381440/860244938037788712/Minecraft__1.16.5_-_Cok_Oyunculu_3._Taraf_Sunucu_2021-07-01_22-41-00.mp4

Slimefun version: Release Candidate 24 (git 588bc)
Slimefun Warfare version: DEV 43 (git dd4dd)

**Comment by Coder-TheSid** [comment]
Server version: git-Purpur-1171 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

**Comment by Seggan** [comment]
First, dont use release candidates, use DEV versions. second, show me your log

**Comment by Seggan** [comment]
Closing until further info
