### ISSUE TITLE
Meteor attractor

### ISSUE THREAD

**Issue by jigglypuff2731** [Seggan/SlimefunWarfare#30]
Meteor attractor doesn’t work after I built the multiblock and if this isn’t a bug and there’s something I have to do the slimefun guide says nothing about it just a magnet so strong that it can pull meteors from space. That’s it nothing else

**Comment by Seggan** [comment]
right click the bottom block

**Comment by jigglypuff2731** [comment]
Is there something else or what

**Comment by jigglypuff2731** [comment]
I tried that like an hour ago nothing

**Comment by Seggan** [comment]
hmm. ill see what i can do

**Comment by Seggan** [comment]
The meteor attractor has been condensed into a single block in the latest update and now works
