### ISSUE TITLE
SF-Warfare does not work after restarting server on 1.19.2

### ISSUE THREAD

**Issue by DuckStuffedwastaken** [Seggan/SlimefunWarfare#45]
While I was playing on my 1.19.2 spigot server, after I restarted it (Or just turned it off) the plugin would no longer function, i.e. it wasn't showing up in the guide, nor did it appear when I searched for any of the plugin's items.

**Comment by Seggan** [comment]
Errors? Server logs? You have given me no info.

**Comment by Seggan** [comment]
CLosing until further information given
