### ISSUE TITLE
Explosive Synthesizer has incorrect interaction with cargo

### ISSUE THREAD

**Issue by GallowsDove** [Seggan/SlimefunWarfare#6]
Explosive Synthesizer gets filled up with given material, instead of getting only one stack of the given material like Electric Smeltery.

E.g. when I put in coal and I have a lot of coal but not enough pure liquified nitrogen, it gets filled with coal and will stop producing until coal is manually removed.

Explosive Synthesizer
![image](https://user-images.githubusercontent.com/71831019/102019677-1eac2c00-3d75-11eb-89a8-8e5f9db3226f.png)

**Comment by Seggan** [comment]
Can you provide a screenshot of the bug?

**Comment by GallowsDove** [comment]
Im sorry, Im currently away, but just imagine 2 stacks of coal in the synthesizer, which in my opinion shouldn't happen, there should be only 1 stack of coal and it should wait until more liquid nitrogen is available. (like electric smeltery)

**Comment by Boomer-1** [comment]
that's not a bug
