### ISSUE TITLE
Weapons able to kill in residences

### ISSUE THREAD

**Issue by GallowsDove** [Seggan/SlimefunWarfare#7]
Player is able to kill animals in residences even with disabled animalkilling

**Comment by Seggan** [comment]
please run /sf versions and give me result. also, are there any errors in console? @GallowsDove

**Comment by GallowsDove** [comment]
No errors, for versions you can refer to #6, it's the same.

**Comment by GallowsDove** [comment]
Another related (possible) issue is that you can kill and damage players in residences with granades.

**Comment by Seggan** [comment]
Looking at Residence 's [source code](https://github.com/bekvon/Residence), it appears o be a Residence issue, as they do not have a BlockExplodeEvent listener or a check for any other projectile other than arrows. I will make a bug report and attempt to make a pull request.

**Comment by Seggan** [comment]
Also, residence seems to not be in development anymore

**Comment by DartCZ** [comment]
Hello,

there is active Residence fork now https://github.com/Zrips/Residence

**Comment by Seggan** [comment]
@DartCZ thank you, I will open my issue there

**Comment by Seggan** [comment]
As it is their problem, i will close this
